before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
     - -s -w -X github.com/enginyoyen/mimic/pkg/cmd.Version={{.Version}} -X github.com/enginyoyen/mimic/pkg/cmd.GitCommit={{.Commit}} -X github.com/enginyoyen/mimic/pkg/cmd.BuildTime={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    name: mimic
    tap:
      owner: enginyoyen
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    url_template: "https://github.com/enginyoyen/mimic/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    homepage: "https://github.com/enginyoyen/mimic"
    description: "Mimic is standalone HTTP-based mock server."
    license: "MIT"
    skip_upload: true

    test: |
      system "#{bin}/mimic --version"

    install: |
      bin.install "program"
    